# Generated by Django 4.2.7 on 2023-12-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='id_aluno',
            new_name='aluno',
        ),
    ]
