# Generated by Django 4.2.7 on 2023-12-02 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro_app', '0005_exercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='id',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro_app.disciplina'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='username',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AlunoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_app.disciplina')),
            ],
        ),
    ]
